version: '3' # specify docker-compose version

# Define the services/containers to be run
services:
  angular:
    container_name: angular
    build: projectN-angular-docker # specify the directory of the Dockerfile
    ports:
      - "4200:4200" # specify port forewarding
    volumes:
      - ./projectN-angular-docker/src:/app/src # this will enable changes made to the angular app reflect in the container
    tty: true

  nest:
    container_name: nestjs_api_dev
    build: projectN-nest-docker
    command: npm run start:dev
    tty: true
    ports:
      - 3000:3000
    volumes:
      - ./projectN-nest-docker/src:/app/src
      - ./projectN-nest-docker/migration:/app/migartion
      - ./projectN-nest-docker/package.json:/app/package.json
      #dist??




  # database:
  #   image: mariadb # specify image to build container from
  #   restart: 'always'
  #   # volumes:
  #   #   - ./mariadb/db.cnf:/etc/mysql/db.cnf
  #   environment:
  #     MYSQL_ROOT_PASSWORD: "Unick"
  #   ports:
  #     - "3306:3306"